package form;

public class dashboardpengajar extends BaseFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboardpengajar.class.getName());

    /**
     * Creates new form dashboardpengajar
     */
    String email;

public dashboardpengajar(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    

    centerWindow();
    this.email = email;

    String nama = email.split("@")[0];
    txtpengajar2.setText("Selamat Datang " + nama);
}
    
    @Override
    public void tampilRole() {
        System.out.println("Ini dashboard Pengajar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpengajar = new javax.swing.JLabel();
        txtpengajar2 = new javax.swing.JLabel();
        tmbKehadiran = new javax.swing.JButton();
        tmbDataSiswa = new javax.swing.JButton();
        tmbDataRuangan = new javax.swing.JButton();
        tmbJadwal = new javax.swing.JButton();
        tmbLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtpengajar.setText("DASHBOARD PENGAJAR");

        txtpengajar2.setText("Selamat Datang");

        tmbKehadiran.setBackground(new java.awt.Color(255, 102, 153));
        tmbKehadiran.setText("Data Kehadiran");
        tmbKehadiran.addActionListener(this::tmbKehadiranActionPerformed);

        tmbDataSiswa.setBackground(new java.awt.Color(255, 102, 153));
        tmbDataSiswa.setText("Data Siswa");
        tmbDataSiswa.addActionListener(this::tmbDataSiswaActionPerformed);

        tmbDataRuangan.setBackground(new java.awt.Color(255, 153, 204));
        tmbDataRuangan.setText("Data Ruangan");
        tmbDataRuangan.addActionListener(this::tmbDataRuanganActionPerformed);

        tmbJadwal.setBackground(new java.awt.Color(255, 153, 204));
        tmbJadwal.setText("Jadwal");
        tmbJadwal.addActionListener(this::tmbJadwalActionPerformed);

        tmbLogout.setBackground(new java.awt.Color(204, 255, 204));
        tmbLogout.setText("LOGOUT");
        tmbLogout.addActionListener(this::tmbLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tmbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmbDataRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmbDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmbKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tmbLogout)
                        .addGap(306, 306, 306))))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpengajar2)
                    .addComponent(txtpengajar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtpengajar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpengajar2)
                .addGap(18, 18, 18)
                .addComponent(tmbDataSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbDataRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbKehadiran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tmbLogout)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbKehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKehadiranActionPerformed
         new datakehadiran(email).setVisible(true); // 🔥 FULL AKSES
    this.dispose();
    }//GEN-LAST:event_tmbKehadiranActionPerformed

    private void tmbDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataSiswaActionPerformed
        new datasiswa("pengajar").setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbDataSiswaActionPerformed

    private void tmbJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbJadwalActionPerformed
        new datajadwal(email).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbJadwalActionPerformed

    private void tmbDataRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataRuanganActionPerformed
        new dataruangan("pengajar").setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbDataRuanganActionPerformed

    private void tmbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbLogoutActionPerformed
        new formlogin().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboardpengajar("pengajar@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton tmbDataRuangan;
    private javax.swing.JButton tmbDataSiswa;
    private javax.swing.JButton tmbJadwal;
    private javax.swing.JButton tmbKehadiran;
    private javax.swing.JButton tmbLogout;
    private javax.swing.JLabel txtpengajar;
    private javax.swing.JLabel txtpengajar2;
    // End of variables declaration//GEN-END:variables
}
