package form;

public class dashboardadmin extends BaseFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboardadmin.class.getName());

    /**
     * Creates new form dashboardadmin
     */
    String email;

    public dashboardadmin() {
    initComponents();
    
    }
    
public dashboardadmin(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    
    centerWindow();
    this.email = email;

    String nama = email.split("@")[0];
    jLabel2.setText("Selamat Datang " + nama);
}
    
    public void tampilRole() {
        System.out.println("Ini dashboard Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tmbDataSiswa = new javax.swing.JButton();
        tmbDataPengajar = new javax.swing.JButton();
        tmbJadwal = new javax.swing.JButton();
        tmbDaftarHadir = new javax.swing.JButton();
        tmbDataRuangan = new javax.swing.JButton();
        tmbLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DASHBOARD ADMIN");

        jLabel2.setText("Selamat Datang");

        tmbDataSiswa.setBackground(new java.awt.Color(255, 102, 153));
        tmbDataSiswa.setText("Data Siswa");
        tmbDataSiswa.addActionListener(this::tmbDataSiswaActionPerformed);

        tmbDataPengajar.setBackground(new java.awt.Color(255, 153, 204));
        tmbDataPengajar.setText("Data Pengajar");
        tmbDataPengajar.addActionListener(this::tmbDataPengajarActionPerformed);

        tmbJadwal.setBackground(new java.awt.Color(255, 102, 153));
        tmbJadwal.setText("Jadwal");
        tmbJadwal.addActionListener(this::tmbJadwalActionPerformed);

        tmbDaftarHadir.setBackground(new java.awt.Color(255, 153, 204));
        tmbDaftarHadir.setText("Daftar Hadir");
        tmbDaftarHadir.addActionListener(this::tmbDaftarHadirActionPerformed);

        tmbDataRuangan.setBackground(new java.awt.Color(255, 102, 153));
        tmbDataRuangan.setText("Data Ruangan");
        tmbDataRuangan.addActionListener(this::tmbDataRuanganActionPerformed);

        tmbLogout.setBackground(new java.awt.Color(204, 255, 204));
        tmbLogout.setText("LOGOUT");
        tmbLogout.addActionListener(this::tmbLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tmbLogout)
                        .addGap(307, 307, 307))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tmbDaftarHadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tmbDataRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addComponent(tmbDataPengajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tmbDataSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tmbJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tmbDataSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbDataPengajar)
                .addGap(12, 12, 12)
                .addComponent(tmbDataRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbDaftarHadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbJadwal)
                .addGap(18, 18, 18)
                .addComponent(tmbLogout)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbDataPengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataPengajarActionPerformed
        new datapengajar(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbDataPengajarActionPerformed

    private void tmbDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataSiswaActionPerformed
        new datasiswa(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbDataSiswaActionPerformed

    private void tmbDataRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataRuanganActionPerformed
        new dataruangan(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbDataRuanganActionPerformed

    private void tmbJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbJadwalActionPerformed
        new datajadwal(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbJadwalActionPerformed

    private void tmbDaftarHadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDaftarHadirActionPerformed
        new datakehadiran(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbDaftarHadirActionPerformed

    private void tmbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbLogoutActionPerformed
        new formlogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboardadmin("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tmbDaftarHadir;
    private javax.swing.JButton tmbDataPengajar;
    private javax.swing.JButton tmbDataRuangan;
    private javax.swing.JButton tmbDataSiswa;
    private javax.swing.JButton tmbJadwal;
    private javax.swing.JButton tmbLogout;
    // End of variables declaration//GEN-END:variables

// 🔥 TARUH DI SINI (MASIH DI DALAM FILE, TAPI DI LUAR CLASS UTAMA)
    class AdminUser extends UserAbstract {

    public AdminUser(String nama) {
        super(nama);
    }

    @Override
    public void tampilUser() {
        System.out.println("Admin: " + nama);
    }
    }
}