package form;

public class dashboardsiswa extends BaseFrame {
    private int idSiswa;
    private String namaSiswa;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboardsiswa.class.getName());

    /**
     * Creates new form dashboardsiswa
     */
    public dashboardsiswa() {
    initComponents();
    centerWindow();
    tampilRole();
    
    SiswaUser user = new SiswaUser("Siswa");
    user.tampilUser();
}
    String email;

public dashboardsiswa(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    centerWindow();
    this.email = email;

    String nama = email.split("@")[0];
    txtsiswa2.setText("Selamat Datang " + nama);
}
    
    @Override
    public void tampilRole() {
        System.out.println("Ini dashboard Siswa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsiswa = new javax.swing.JLabel();
        txtsiswa2 = new javax.swing.JLabel();
        tmbJadwal = new javax.swing.JButton();
        tmbDataRuangan = new javax.swing.JButton();
        tmbLogout = new javax.swing.JButton();
        tmbDataKehadiran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtsiswa.setText("DASHBOARD SISWA");

        txtsiswa2.setText("Selamat Datang");

        tmbJadwal.setBackground(new java.awt.Color(255, 102, 153));
        tmbJadwal.setText("Jadwal");
        tmbJadwal.addActionListener(this::tmbJadwalActionPerformed);

        tmbDataRuangan.setBackground(new java.awt.Color(255, 102, 153));
        tmbDataRuangan.setText("Data Ruangan");
        tmbDataRuangan.addActionListener(this::tmbDataRuanganActionPerformed);

        tmbLogout.setBackground(new java.awt.Color(204, 255, 204));
        tmbLogout.setText("LOGOUT");
        tmbLogout.addActionListener(this::tmbLogoutActionPerformed);

        tmbDataKehadiran.setBackground(new java.awt.Color(255, 153, 204));
        tmbDataKehadiran.setText("Data Kehadiran");
        tmbDataKehadiran.addActionListener(this::tmbDataKehadiranActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tmbJadwal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tmbDataRuangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tmbDataKehadiran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tmbLogout)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsiswa2)
                            .addComponent(txtsiswa))
                        .addGap(292, 292, 292))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtsiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsiswa2)
                .addGap(18, 18, 18)
                .addComponent(tmbDataRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbDataKehadiran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbJadwal)
                .addGap(18, 18, 18)
                .addComponent(tmbLogout)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbDataKehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataKehadiranActionPerformed
        new datakehadiransiswa(email, idSiswa, namaSiswa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbDataKehadiranActionPerformed

    private void tmbJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbJadwalActionPerformed
        new datajadwal("siswa").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbJadwalActionPerformed

    private void tmbDataRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbDataRuanganActionPerformed
        new dataruangan("siswa").setVisible(true);         
        this.dispose();
    }//GEN-LAST:event_tmbDataRuanganActionPerformed

    private void tmbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbLogoutActionPerformed
         new formlogin().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_tmbLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboardsiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton tmbDataKehadiran;
    private javax.swing.JButton tmbDataRuangan;
    private javax.swing.JButton tmbJadwal;
    private javax.swing.JButton tmbLogout;
    private javax.swing.JLabel txtsiswa;
    private javax.swing.JLabel txtsiswa2;
    // End of variables declaration//GEN-END:variables
}

class SiswaUser extends UserAbstract {

    public SiswaUser(String nama) {
        super(nama);
    }

    @Override
    public void tampilUser() {
        System.out.println("Siswa: " + nama);
    }
}