package form;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class datakehadiran extends javax.swing.JFrame {
    String email;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(datakehadiran.class.getName());

    /**
     * Creates new form datakehadiran
     */
    
public datakehadiran() {
    initComponents();
tmbHapus.setVisible(false);
    this.email = "admin@gmail.com"; // biar ga null
    loadData();
}
    
    public datakehadiran(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    
    this.email = email;

    txtDataKehadiran.setText("Data Kehadiran - " + email.split("@")[0]);

    loadData();
}
    
    private void loadData() {
    try {
        Connection conn = Koneksi.getConnection();
        Statement st = conn.createStatement();

        String sql = "SELECT s.id_siswa, s.nama, " +
             "IFNULL(k.status, 'Alpha') AS status " +
             "FROM siswa s " +
             "LEFT JOIN kehadiran k " +
             "ON s.id_siswa = k.id_siswa";

        ResultSet rs = st.executeQuery(sql);

        DefaultTableModel model = (DefaultTableModel) tblKehadiran.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            
          model.addRow(new Object[]{
    rs.getInt("id_siswa"),
    rs.getString("nama"),
    "",
    "",
    rs.getString("status")
});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDataKehadiran = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKehadiran = new javax.swing.JTable();
        tmbEdit = new javax.swing.JButton();
        tmbHapus = new javax.swing.JButton();
        tmbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDataKehadiran.setText("DATA KEHADIRAN");

        tblKehadiran.setBackground(new java.awt.Color(255, 153, 204));
        tblKehadiran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Siswa", "Pengajar", "Tanggal", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblKehadiran);

        tmbEdit.setBackground(new java.awt.Color(255, 102, 153));
        tmbEdit.setText("EDIT");
        tmbEdit.addActionListener(this::tmbEditActionPerformed);

        tmbHapus.setBackground(new java.awt.Color(255, 102, 153));
        tmbHapus.setText("HAPUS");
        tmbHapus.addActionListener(this::tmbHapusActionPerformed);

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txtDataKehadiran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tmbEdit)
                        .addGap(18, 18, 18)
                        .addComponent(tmbHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tmbKembali))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDataKehadiran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbEdit)
                    .addComponent(tmbHapus)
                    .addComponent(tmbKembali))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
if (email != null && email.contains("admin")) {
    new dashboardadmin(email).setVisible(true);
} else if (email != null && email.contains("pengajar")) {
    new dashboardpengajar(email).setVisible(true);
} else {
    new dashboardsiswa(email).setVisible(true);
}
this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    private void tmbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbHapusActionPerformed
       int baris = tblKehadiran.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(tblKehadiran.getValueAt(baris, 0).toString());

    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus?");

    if (konfirmasi == 0) {
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "DELETE FROM kehadiran WHERE id_kehadiran=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadData(); // refresh

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_tmbHapusActionPerformed

    private void tmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbEditActionPerformed
          
    int baris = tblKehadiran.getSelectedRow();

    if (baris != -1) {

        int id = Integer.parseInt(
            tblKehadiran.getValueAt(baris, 0).toString()
        );

        String siswa =
            tblKehadiran.getValueAt(baris, 1).toString();

        String pengajar =
            tblKehadiran.getValueAt(baris, 2).toString();

        String tanggal =
            tblKehadiran.getValueAt(baris, 3).toString();

        String status =
            tblKehadiran.getValueAt(baris, 4).toString();

        new formkehadiran(
            id,
            siswa,
            pengajar,
            "",
            "",
            "",
            status
        ).setVisible(true);

        this.dispose();

    } else {

        JOptionPane.showMessageDialog(this,
            "Pilih data dulu!");

    }
    }//GEN-LAST:event_tmbEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new datakehadiran("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKehadiran;
    private javax.swing.JButton tmbEdit;
    private javax.swing.JButton tmbHapus;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JLabel txtDataKehadiran;
    // End of variables declaration//GEN-END:variables
}
