package form;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class datasiswa extends javax.swing.JFrame {
    String email;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(datasiswa.class.getName());

    /**
     * Creates new form datasiswa
     */
    public datasiswa() {
        initComponents();    
        this.email = "admin@gmail.com"; 
        loadData();
    }
    
public datasiswa(String email) {
    initComponents();
    
            setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    this.email = email;

    if (!email.contains("admin")) {
        tmbTambah.setVisible(false);
        tmbEdit.setVisible(false);
        tmbHapus.setVisible(false);
    }

    loadData();
}
    
    private void loadData() {
    try {
        java.sql.Connection conn = koneksi.Koneksi.getConnection();
        java.sql.Statement st = conn.createStatement();
        String sql = "SELECT id_siswa, nama, alamat, no_hp, email FROM siswa";

        java.sql.ResultSet rs = st.executeQuery(sql);

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0); // kosongkan tabel

        while (rs.next()) {
            model.addRow(new Object[]{
    rs.getInt("id_siswa"),
    rs.getString("nama"),
    rs.getString("alamat"),
    rs.getString("no_hp"),
    rs.getString("email")
});        
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDataSiswa = new javax.swing.JLabel();
        tmbEdit = new javax.swing.JButton();
        tmbHapus = new javax.swing.JButton();
        tmbTambah = new javax.swing.JButton();
        tmbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(255, 153, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nama", "Alamat", "No HP", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtDataSiswa.setText("DATA SISWA");

        tmbEdit.setBackground(new java.awt.Color(255, 102, 153));
        tmbEdit.setText("EDIT");
        tmbEdit.addActionListener(this::tmbEditActionPerformed);

        tmbHapus.setBackground(new java.awt.Color(255, 102, 153));
        tmbHapus.setText("HAPUS");
        tmbHapus.addActionListener(this::tmbHapusActionPerformed);

        tmbTambah.setBackground(new java.awt.Color(255, 102, 153));
        tmbTambah.setText("TAMBAH");
        tmbTambah.addActionListener(this::tmbTambahActionPerformed);

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 311, Short.MAX_VALUE)
                        .addComponent(txtDataSiswa)
                        .addGap(313, 313, 313))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tmbEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tmbHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tmbTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tmbKembali)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDataSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbEdit)
                    .addComponent(tmbHapus)
                    .addComponent(tmbTambah)
                    .addComponent(tmbKembali))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbTambahActionPerformed
         new formsiswa().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_tmbTambahActionPerformed

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
if (email != null && email.contains("admin")) {
    new dashboardadmin(email).setVisible(true);
} else if (email.contains("pengajar")) {
    new dashboardpengajar(email).setVisible(true);
} else {
    new dashboardsiswa(email).setVisible(true);
}
    this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    private void tmbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbHapusActionPerformed
        int baris = jTable1.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(jTable1.getValueAt(baris, 0).toString());

    int konfirmasi = JOptionPane.showConfirmDialog(this,
        "Yakin ingin menghapus data?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "DELETE FROM siswa WHERE id_siswa=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

            loadData(); // 🔥 refresh tabel

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_tmbHapusActionPerformed

    private void tmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbEditActionPerformed
    int baris = jTable1.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id_siswa = Integer.parseInt(jTable1.getValueAt(baris, 0).toString());
    String nama = jTable1.getValueAt(baris, 1).toString();
    String alamat = jTable1.getValueAt(baris, 2).toString();
    String hp = jTable1.getValueAt(baris, 3).toString();

    new formsiswa(id_siswa, nama, alamat, hp).setVisible(true);
    
    }//GEN-LAST:event_tmbEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new datasiswa("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tmbEdit;
    private javax.swing.JButton tmbHapus;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JButton tmbTambah;
    private javax.swing.JLabel txtDataSiswa;
    // End of variables declaration//GEN-END:variables
}
