package form;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class dataruangan extends javax.swing.JFrame {
    String email;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dataruangan.class.getName());

    /**
     * Creates new form dataruangan
     */
public dataruangan() {
    initComponents();
    this.email = "admin@gmail.com"; // biar ga null
    loadData();
}

public dataruangan(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    
    this.email = email;

    if (!email.contains("admin")) {
        tmbTambah.setVisible(false);
        tmbEdit.setVisible(false);
        tmbHapus.setVisible(false);
    }

    loadData();
}
    private void loadData() {
    try {
        Connection conn = Koneksi.getConnection();
        ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM ruangan");

        DefaultTableModel model = (DefaultTableModel) tblRuangan.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_ruangan"),
                rs.getString("nama_ruangan"),
                rs.getInt("kapasitas")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRuangan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuangan = new javax.swing.JTable();
        tmbEdit = new javax.swing.JButton();
        tmbHapus = new javax.swing.JButton();
        tmbTambah = new javax.swing.JButton();
        tmbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRuangan.setText("DATA RUANGAN");

        tblRuangan.setBackground(new java.awt.Color(255, 153, 204));
        tblRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nama Ruangan", "Kapasitas"
            }
        ));
        jScrollPane1.setViewportView(tblRuangan);

        tmbEdit.setBackground(new java.awt.Color(255, 102, 153));
        tmbEdit.setText("EDIT");
        tmbEdit.addActionListener(this::tmbEditActionPerformed);

        tmbHapus.setBackground(new java.awt.Color(255, 102, 153));
        tmbHapus.setText("HAPUS");
        tmbHapus.addActionListener(this::tmbHapusActionPerformed);

        tmbTambah.setBackground(new java.awt.Color(255, 102, 153));
        tmbTambah.setText("TAMBAH");
        tmbTambah.addActionListener(this::tmbTambahActionPerformed);

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tmbEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tmbHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tmbTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tmbKembali)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(txtRuangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbEdit)
                    .addComponent(tmbHapus)
                    .addComponent(tmbTambah)
                    .addComponent(tmbKembali))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbHapusActionPerformed
         int baris = tblRuangan.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(tblRuangan.getValueAt(baris, 0).toString());

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "DELETE FROM ruangan WHERE id_ruangan=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        loadData();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_tmbHapusActionPerformed

    private void tmbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbTambahActionPerformed
        new formruangan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbTambahActionPerformed

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
if (email != null && email.contains("admin")) {
    new dashboardadmin(email).setVisible(true);
} else if (email != null && email.contains("pengajar")) {
    new dashboardpengajar(email).setVisible(true);
} else {
    new dashboardsiswa(email).setVisible(true);
}
this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    private void tmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbEditActionPerformed
        int baris = tblRuangan.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(tblRuangan.getValueAt(baris, 0).toString());
    String nama = tblRuangan.getValueAt(baris, 1).toString();
    String kapasitas = tblRuangan.getValueAt(baris, 2).toString();

    new formruangan(id, nama, kapasitas).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new dataruangan("admin@gmail.com").setVisible(true);
    }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRuangan;
    private javax.swing.JButton tmbEdit;
    private javax.swing.JButton tmbHapus;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JButton tmbTambah;
    private javax.swing.JLabel txtRuangan;
    // End of variables declaration//GEN-END:variables
}
