package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import java.text.SimpleDateFormat;

public class datakehadiransiswa extends javax.swing.JFrame {
    String email;
    private int idSiswa;
    private String namaSiswa;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(datakehadiransiswa.class.getName());

    /**
     * Creates new form datakehadiransiswa
     */

    public datakehadiransiswa(String email, int idSiswa, String namaSiswa) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());

    this.email = email;
    this.idSiswa = idSiswa;
    this.namaSiswa = namaSiswa;

    txtSelamatDatang.setText("Selamat Datang " + namaSiswa);

    loadData();
    loadRekap();
}

public datakehadiransiswa(String email) {
    initComponents();
    this.email = email;

    String nama = email.split("@")[0];
    txtSelamatDatang.setText("Selamat Datang " + nama);
}
    
    private void loadData() {
    try {
        Connection conn = Koneksi.getConnection();

        String sql = "SELECT k.tanggal, j.hari, j.jam, p.nama AS pengajar, k.status " +
                     "FROM kehadiran k " +
                     "JOIN jadwal j ON k.id_jadwal = j.id " +
                     "JOIN pengajar p ON j.id_pengajar = p.id_pengajar " +
                     "WHERE j.id_siswa = ?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idSiswa);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblKehadiran.getModel();
        model.setRowCount(0);

        while (rs.next()) {

            java.util.Date date = rs.getDate("tanggal");
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String tanggal = sdf.format(date);

            model.addRow(new Object[]{
                tanggal,
                rs.getString("hari"),
                rs.getString("jam"),
                rs.getString("pengajar"),
                rs.getString("status")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void loadRekap() {
    try {
        Connection conn = Koneksi.getConnection();

        String sql = "SELECT status, COUNT(*) AS total " +
                     "FROM kehadiran k " +
                     "JOIN jadwal j ON k.id_jadwal = j.id " +
                     "WHERE j.id_siswa = ? " +
                     "GROUP BY status";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idSiswa);

        ResultSet rs = pst.executeQuery();

        int hadir = 0, izin = 0, sakit = 0, alpha = 0;

        while (rs.next()) {
            String status = rs.getString("status");

            if (status.equals("Hadir")) hadir = rs.getInt("total");
            if (status.equals("Izin")) izin = rs.getInt("total");
            if (status.equals("Sakit")) sakit = rs.getInt("total");
            if (status.equals("Alpha")) alpha = rs.getInt("total");
        }

        txtHadir.setText("Hadir : " + hadir);
        txtIzin.setText("Izin : " + izin);
        txtSakit.setText("Sakit : " + sakit);
        txtAlpha.setText("Alpha : " + alpha);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSelamatDatang = new javax.swing.JLabel();
        txtHadir = new javax.swing.JLabel();
        txtIzin = new javax.swing.JLabel();
        txtSakit = new javax.swing.JLabel();
        txtAlpha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKehadiran = new javax.swing.JTable();
        tmbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSelamatDatang.setText("WELCOME!");

        txtHadir.setText("HADIR");

        txtIzin.setText("IZIN");

        txtSakit.setText("SAKIT");

        txtAlpha.setText("ALPHA");

        tblKehadiran.setBackground(new java.awt.Color(255, 153, 204));
        tblKehadiran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Hari", "Jam", "Pengajar", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblKehadiran);

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHadir)
                            .addComponent(txtAlpha))
                        .addGap(0, 651, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSelamatDatang)
                .addGap(315, 315, 315))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIzin)
                    .addComponent(txtSakit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tmbKembali)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSelamatDatang)
                .addGap(18, 18, 18)
                .addComponent(txtHadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIzin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSakit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlpha)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tmbKembali)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
        new dashboardsiswa(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new datakehadiransiswa("siswa@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKehadiran;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JLabel txtAlpha;
    private javax.swing.JLabel txtHadir;
    private javax.swing.JLabel txtIzin;
    private javax.swing.JLabel txtSakit;
    private javax.swing.JLabel txtSelamatDatang;
    // End of variables declaration//GEN-END:variables
}
