package form;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class datajadwal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(datajadwal.class.getName());

    /**
     * Creates new form datajadwal
     */
    
    public datajadwal() {
    initComponents();
    tmbHapus.setText("HAPUS");
tmbHapus.addActionListener(this::tmbHapusActionPerformed);
    loadData();
}
    
private String email;

public datajadwal(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    this.email = email;

    loadData();
    
    if (email != null && email.contains("siswa")) {
    tmbTambah.setVisible(false);
    tmbEdit.setVisible(false);
    tmbHapus.setVisible(false);
}
}

    private void loadData() {
    try {
        Connection conn = Koneksi.getConnection();

       String sql = "SELECT j.id_jadwal, " +
             "p.nama_pengajar AS pengajar, " +
             "s.nama AS siswa, " +
             "r.nama_ruangan, " +
             "j.hari, j.jam " +
             "FROM jadwal j " +
             "JOIN pengajar p ON j.id_pengajar = p.id_pengajar " +
             "JOIN siswa s ON j.id_siswa = s.id_siswa " +
             "JOIN ruangan r ON j.id_ruangan = r.id_ruangan";

        ResultSet rs = conn.createStatement().executeQuery(sql);

        DefaultTableModel model = (DefaultTableModel) tblJadwal.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_jadwal"),
                rs.getString("pengajar"),
                rs.getString("siswa"),
                rs.getString("hari"),
                rs.getString("jam"),
                rs.getString("nama_ruangan")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJadwal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        tmbEdit = new javax.swing.JButton();
        tmbHapus = new javax.swing.JButton();
        tmbTambah = new javax.swing.JButton();
        tmbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJadwal.setText("JADWAL");

        tblJadwal.setBackground(new java.awt.Color(255, 153, 204));
        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Pengajar", "Siswa", "Hari", "Jam", "Ruangan"
            }
        ));
        jScrollPane1.setViewportView(tblJadwal);

        tmbEdit.setBackground(new java.awt.Color(255, 102, 153));
        tmbEdit.setLabel("EDIT");
        tmbEdit.addActionListener(this::tmbEditActionPerformed);

        tmbHapus.setBackground(new java.awt.Color(255, 102, 153));
        tmbHapus.setText("HAPUS");

        tmbTambah.setBackground(new java.awt.Color(255, 102, 153));
        tmbTambah.setText("TAMBAH");
        tmbTambah.addActionListener(this::tmbTambahActionPerformed);

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tmbEdit)
                        .addGap(18, 18, 18)
                        .addComponent(tmbHapus)
                        .addGap(18, 18, 18)
                        .addComponent(tmbTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tmbKembali)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(txtJadwal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbEdit)
                    .addComponent(tmbHapus)
                    .addComponent(tmbTambah)
                    .addComponent(tmbKembali))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbTambahActionPerformed
        new formjadwal(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbTambahActionPerformed

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
if (email != null && email.contains("admin")) {
    new dashboardadmin(email).setVisible(true);
} else if (email != null && email.contains("pengajar")) {
    new dashboardpengajar(email).setVisible(true);
} else {
    new dashboardsiswa(email).setVisible(true);
}
this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    private void tmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbEditActionPerformed
        int baris = tblJadwal.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(tblJadwal.getValueAt(baris, 0).toString());
    String pengajar = tblJadwal.getValueAt(baris, 1).toString();
    String siswa = tblJadwal.getValueAt(baris, 2).toString();
    String hari = tblJadwal.getValueAt(baris, 3).toString();
    String jam = tblJadwal.getValueAt(baris, 4).toString();
    String ruangan = tblJadwal.getValueAt(baris, 5).toString();

    new formjadwal(
    email,
    id,
    pengajar,
    siswa,
    hari,
    jam,
    ruangan
).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbEditActionPerformed

    private void tmbHapusActionPerformed(java.awt.event.ActionEvent evt) {
    if (email != null && email.contains("siswa")) {
    JOptionPane.showMessageDialog(this, "Siswa tidak punya akses!");
    return;
}
        
        int baris = tblJadwal.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin mau hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            int id = Integer.parseInt(tblJadwal.getValueAt(baris, 0).toString());

            Connection conn = Koneksi.getConnection();
            String sql = "DELETE FROM jadwal WHERE id_jadwal=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

            loadData(); // refresh tabel

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new datajadwal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJadwal;
    private javax.swing.JButton tmbEdit;
    private javax.swing.JButton tmbHapus;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JButton tmbTambah;
    private javax.swing.JLabel txtJadwal;
    // End of variables declaration//GEN-END:variables
}
