package form;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;


public class datapengajar extends javax.swing.JFrame {
    String email;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(datapengajar.class.getName());

    /**
     * Creates new form datapengajar
     */
   public datapengajar() {
    initComponents();
    this.email = "admin@gmail.com";
    loadData();

    setSize(720, 350); // 🔥 WAJIB TAMBAH INI
    setLocationRelativeTo(null);
}
   
   public datapengajar(String email) {
    initComponents();
    
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
    
    this.email = email;

    if (email == null || !email.contains("admin")) {
    tmbTambah.setVisible(false);
    tmbEdit.setVisible(false);
    tmbHapus.setVisible(false);
}

    loadData();
}
    
    private void loadData() {
    try {
        Connection conn = Koneksi.getConnection();
        Statement st = conn.createStatement();
        String sql = "SELECT p.*, u.email " +
             "FROM pengajar p " +
             "JOIN users u ON p.id_pengajar = u.id_user";

        ResultSet rs = st.executeQuery(sql);

        DefaultTableModel model = (DefaultTableModel) tblPengajar.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_pengajar"),
                rs.getString("nama_pengajar"),
                rs.getString("no_hp"),
                rs.getString("email")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengajar = new javax.swing.JTable();
        tmbEdit = new javax.swing.JButton();
        tmbHapus = new javax.swing.JButton();
        tmbTambah = new javax.swing.JButton();
        tmbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA PENGAJAR");

        tblPengajar.setBackground(new java.awt.Color(255, 153, 204));
        tblPengajar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "No HP", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblPengajar);

        tmbEdit.setBackground(new java.awt.Color(255, 102, 153));
        tmbEdit.setText("EDIT");
        tmbEdit.addActionListener(this::tmbEditActionPerformed);

        tmbHapus.setBackground(new java.awt.Color(255, 102, 153));
        tmbHapus.setText("HAPUS");
        tmbHapus.addActionListener(this::tmbHapusActionPerformed);

        tmbTambah.setBackground(new java.awt.Color(255, 102, 153));
        tmbTambah.setText("TAMBAH");
        tmbTambah.addActionListener(this::tmbTambahActionPerformed);

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tmbEdit)
                        .addGap(19, 19, 19)
                        .addComponent(tmbHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tmbTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278)
                        .addComponent(tmbKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tmbEdit)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tmbHapus)
                            .addComponent(tmbTambah)
                            .addComponent(tmbKembali))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbTambahActionPerformed
                                        
    new formpengajar().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_tmbTambahActionPerformed

    private void tmbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbHapusActionPerformed
        int baris = tblPengajar.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(tblPengajar.getValueAt(baris, 0).toString());

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "DELETE FROM pengajar WHERE id=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        loadData();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_tmbHapusActionPerformed

    private void tmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbEditActionPerformed
        int baris = tblPengajar.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int id = Integer.parseInt(tblPengajar.getValueAt(baris, 0).toString());
    String nama = tblPengajar.getValueAt(baris, 1).toString();
    String hp = tblPengajar.getValueAt(baris, 2).toString();

    new formpengajar(id, nama, hp).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_tmbEditActionPerformed

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
        if (email != null && email.contains("admin")) {
    new dashboardadmin(email).setVisible(true);
} else if (email.contains("pengajar")) {
    new dashboardpengajar(email).setVisible(true);
} else {
    new dashboardsiswa(email).setVisible(true);
}
this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new datapengajar("admin@gmail.com").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPengajar;
    private javax.swing.JButton tmbEdit;
    private javax.swing.JButton tmbHapus;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JButton tmbTambah;
    // End of variables declaration//GEN-END:variables
}
