package form;

import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class formlogin extends javax.swing.JFrame implements Loginable {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formlogin.class.getName());

    public formlogin() {
        initComponents();
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    }
    
    @Override
    public void login() {
        System.out.println("Login dipanggil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labellogin = new javax.swing.JLabel();
        labelemail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        labelpass = new javax.swing.JLabel();
        txttomblogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        labellogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labellogin.setText("LOGIN BNA ACADEMY");
        labellogin.setMaximumSize(new java.awt.Dimension(200, 25));

        labelemail.setText("EMAIL");

        txtEmail.setBackground(new java.awt.Color(255, 153, 204));

        txtpass.setBackground(new java.awt.Color(255, 153, 204));

        labelpass.setText("PASSWORD");

        txttomblogin.setBackground(new java.awt.Color(204, 255, 204));
        txttomblogin.setText("LOGIN");
        txttomblogin.addActionListener(this::txttombloginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(labelpass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(labelemail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(txttomblogin)))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labellogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelemail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(labelpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txttomblogin))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttombloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttombloginActionPerformed
    login();
        try {
        
       Connection conn = Koneksi.getConnection();

        String sql = "SELECT * FROM users WHERE email=? AND password=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtEmail.getText());
        pst.setString(2, txtpass.getText());

        ResultSet rs = pst.executeQuery();

       if (rs.next()) {

            int idUser = rs.getInt("id_user");
            String role = rs.getString("role");
            String email = rs.getString("email");
            
             System.out.println("ROLE DB = [" + role + "]");
             
            JOptionPane.showMessageDialog(this, "Login berhasil sebagai " + role);

            switch (role.trim().toLowerCase()) {

                case "admin":
                    new dashboardadmin(email).setVisible(true);
                    break;

                case "pengajar":
                    new dashboardpengajar(email).setVisible(true);
                    break;

                case "siswa":
                    new dashboardsiswa(email).setVisible(true);
                    break;

                default:
                    JOptionPane.showMessageDialog(this, "Role tidak dikenali!");
            }

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Email atau Password salah!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_txttombloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formlogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labellogin;
    private javax.swing.JLabel labelpass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtpass;
    private javax.swing.JButton txttomblogin;
    // End of variables declaration//GEN-END:variables
}
