package form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import java.sql.Statement;
import java.sql.ResultSet;


public class formsiswa extends javax.swing.JFrame {
    private int idSiswa = 0;
    private boolean isEdit = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formsiswa.class.getName());

    /**
     * Creates new form formsiswa
     */
    public formsiswa() {
        initComponents();
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
        
    }
    public formsiswa(int id, String nama, String alamat, String hp) {
        initComponents();

        jTextNama.setText(nama);
        jTextAlamat.setText(alamat);
        jTextHp.setText(hp);

        this.idSiswa = id;
        this.isEdit = true;

        tmbSimpan.setText("Update");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFormSiswa = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JLabel();
        jTextAlamat = new javax.swing.JTextField();
        txtHP = new javax.swing.JLabel();
        jTextHp = new javax.swing.JTextField();
        tmbBatal = new javax.swing.JButton();
        tmbSimpan = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFormSiswa.setText("FORM SISWA");

        txtNama.setText("NAMA");

        jTextNama.setBackground(new java.awt.Color(255, 102, 153));

        txtAlamat.setText("ALAMAT");

        jTextAlamat.setBackground(new java.awt.Color(255, 153, 204));
        jTextAlamat.addActionListener(this::jTextAlamatActionPerformed);

        txtHP.setText("No HP");

        jTextHp.setBackground(new java.awt.Color(255, 102, 153));

        tmbBatal.setBackground(new java.awt.Color(204, 255, 204));
        tmbBatal.setText("BATAL");
        tmbBatal.addActionListener(this::tmbBatalActionPerformed);

        tmbSimpan.setBackground(new java.awt.Color(204, 255, 204));
        tmbSimpan.setText("SIMPAN");
        tmbSimpan.addActionListener(this::tmbSimpanActionPerformed);

        txtEmail.setText("EMAIL");

        jTextFieldEmail.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setText("PASSWORD");

        jTextFieldPass.setBackground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlamat)
                            .addComponent(txtNama)
                            .addComponent(txtHP)
                            .addComponent(txtEmail)
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFormSiswa)
                            .addComponent(jTextNama)
                            .addComponent(jTextAlamat)
                            .addComponent(jTextHp, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldPass))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tmbSimpan)
                        .addGap(18, 18, 18)))
                .addComponent(tmbBatal)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtFormSiswa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama)
                    .addComponent(jTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHP))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbBatal)
                    .addComponent(tmbSimpan))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlamatActionPerformed

    private void tmbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbSimpanActionPerformed
       try {
        Connection conn = Koneksi.getConnection();

        if (isEdit) {
            String sql = "UPDATE siswa SET nama=?, alamat=?, no_hp=? WHERE id=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, jTextNama.getText());
            pst.setString(2, jTextAlamat.getText());
            pst.setString(3, jTextHp.getText());
            pst.setInt(4, idSiswa);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");

        } else {
            // 🔥 MODE TAMBAH (SISWA + USER)

            String email = jTextFieldEmail.getText();
            String password = jTextFieldPass.getText();

            // validasi
            if (email.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Email dan Password wajib diisi!");
                return;
            }

            // 1. INSERT KE USERS
            String sqlUser = "INSERT INTO users (email, password, role) VALUES (?, ?, 'siswa')";
            PreparedStatement psUser = conn.prepareStatement(sqlUser, Statement.RETURN_GENERATED_KEYS);

            psUser.setString(1, email);
            psUser.setString(2, password);
            psUser.executeUpdate();

            // 2. AMBIL ID USER
            ResultSet rs = psUser.getGeneratedKeys();
            int idUser = 0;

            if (rs.next()) {
                idUser = rs.getInt(1);
            }

            // 3. INSERT KE SISWA
            String sqlSiswa = "INSERT INTO siswa (nama, alamat, no_hp, email, id_user) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement psSiswa = conn.prepareStatement(sqlSiswa);

            psSiswa.setString(1, jTextNama.getText());
            psSiswa.setString(2, jTextAlamat.getText());
            psSiswa.setString(3, jTextHp.getText());
            psSiswa.setString(4, jTextFieldEmail.getText());
            psSiswa.setInt(5, idUser);

            psSiswa.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data siswa & akun berhasil ditambahkan!");
        }

        new datasiswa().setVisible(true);
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_tmbSimpanActionPerformed

    private void tmbBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbBatalActionPerformed
        new datasiswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formsiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextAlamat;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextHp;
    private javax.swing.JTextField jTextNama;
    private javax.swing.JButton tmbBatal;
    private javax.swing.JButton tmbSimpan;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFormSiswa;
    private javax.swing.JLabel txtHP;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables
}
