package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import java.text.SimpleDateFormat;

public class formkehadiran extends javax.swing.JFrame {
    private int idKehadiran = 0;
    private boolean isEdit = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formkehadiran.class.getName());

    /**
     * Creates new form formkehadiran
     */
      
    public formkehadiran()  {
    initComponents();

    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());

    loadStatus();
}
    
    public formkehadiran(
    int id,
    String siswa,
    String pengajar,
    String ruangan,
    String hari,
    String jam,
    String status
) {

    initComponents();

    loadStatus();

    this.idKehadiran = id;
    this.isEdit = true;

    // kosongkan combobox dulu
    jComboBox1.removeAllItems();
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();
    jComboBox4.removeAllItems();
    jComboBox5.removeAllItems();

    // isi data dari tabel kehadiran
    jComboBox1.addItem(siswa);
    jComboBox2.addItem(pengajar);
    jComboBox3.addItem(ruangan);
    jComboBox4.addItem(hari);
    jComboBox5.addItem(jam);

    // disable supaya tidak bisa diubah
    jComboBox1.setEnabled(false);
    jComboBox2.setEnabled(false);
    jComboBox3.setEnabled(false);
    jComboBox4.setEnabled(false);
    jComboBox5.setEnabled(false);

    // status masih bisa diubah
    jComboBoxStatus.setSelectedItem(status);

    tmbSimpan.setText("UPDATE");
}
    private void loadStatus() {
        jComboBoxStatus.addItem("Hadir");
        jComboBoxStatus.addItem("Izin");
        jComboBoxStatus.addItem("Sakit");
        jComboBoxStatus.addItem("Alpha");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtJadwal = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        tmbKembali = new javax.swing.JButton();
        tmbSimpan = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM KEHADIRAN");

        txtJadwal.setText("SISWA");

        txtTanggal.setText("RUANGAN");

        txtStatus.setText("STATUS");

        jComboBoxStatus.setBackground(new java.awt.Color(255, 102, 153));

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        tmbSimpan.setBackground(new java.awt.Color(204, 255, 204));
        tmbSimpan.setText("SIMPAN");
        tmbSimpan.addActionListener(this::tmbSimpanActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("PENGAJAR");

        jLabel3.setText("HARI");

        jLabel4.setText("JAM");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggal)
                    .addComponent(txtJadwal)
                    .addComponent(txtStatus)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox5, 0, 221, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 221, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(tmbSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tmbKembali)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJadwal)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggal)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tmbSimpan)
                            .addComponent(tmbKembali))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbSimpanActionPerformed
     try {

        Connection conn = Koneksi.getConnection();

        String status =
            jComboBoxStatus.getSelectedItem().toString();

        // cek data kehadiran
        String cek =
            "SELECT * FROM kehadiran WHERE id_siswa=?";

        PreparedStatement pstCek =
            conn.prepareStatement(cek);

        pstCek.setInt(1, idKehadiran);

        ResultSet rs = pstCek.executeQuery();

        // kalau data sudah ada -> UPDATE
        if (rs.next()) {

            String update =
                "UPDATE kehadiran SET status=? WHERE id_siswa=?";

            PreparedStatement pstUpdate =
                conn.prepareStatement(update);

            pstUpdate.setString(1, status);
            pstUpdate.setInt(2, idKehadiran);

            pstUpdate.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "Status berhasil diupdate!");

        }

        // kalau belum ada -> INSERT
        else {

            String insert =
                "INSERT INTO kehadiran(id_siswa, status) VALUES (?, ?)";

            PreparedStatement pstInsert =
                conn.prepareStatement(insert);

            pstInsert.setInt(1, idKehadiran);
            pstInsert.setString(2, status);

            pstInsert.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "Data kehadiran berhasil ditambahkan!");
        }

        new datakehadiran().setVisible(true);

        this.dispose();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage());

    }

    }//GEN-LAST:event_tmbSimpanActionPerformed

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
        new datakehadiran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formkehadiran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JButton tmbSimpan;
    private javax.swing.JLabel txtJadwal;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables
}
