package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class formjadwal extends javax.swing.JFrame {
    private String email;
    private int idJadwal = 0;
    private boolean isEdit = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formjadwal.class.getName());

    /**
     * Creates new form formjadwal
     */
    public formjadwal(String email) {

    initComponents();

    this.email = email;
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
        
        loadPengajar();
        loadSiswa();
        loadHari();
        loadJam();
        loadRuangan();
    }
   public formjadwal(
    String email,
    int id,
    String pengajar,
    String siswa,
    String hari,
    String jam,
    String ruangan
) {
    initComponents();
    loadPengajar();
    loadSiswa();
    loadHari();
    loadJam();
    loadRuangan(); // 🔥 wajib

    this.email = email;
    this.idJadwal = id;
    this.isEdit = true;

    jComboBoxPengajar.setSelectedItem(pengajar);
jComboBoxSiswa.setSelectedItem(siswa);
jComboBoxHari.setSelectedItem(hari);
jComboBoxJam.setSelectedItem(jam);
jComboBoxRuangan.setSelectedItem(ruangan);

tmbSimpan.setText("UPDATE");
}
    
   private void loadPengajar() {

    try {

        Connection conn = Koneksi.getConnection();

        String sql = "SELECT * FROM pengajar";

        ResultSet rs =
            conn.createStatement().executeQuery(sql);

        while (rs.next()) {

            jComboBoxPengajar.addItem(
                rs.getInt("id_pengajar") + " - " +
                rs.getString("nama_pengajar")
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage());

    }
}
    private void loadSiswa() {
     try {

        Connection conn = Koneksi.getConnection();

        String sql = "SELECT * FROM siswa";

        ResultSet rs =
            conn.createStatement().executeQuery(sql);

        while (rs.next()) {

            jComboBoxSiswa.addItem(
                rs.getInt("id_siswa") + " - " +
                rs.getString("nama")
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage());

    }
    }
   
    private void loadRuangan() {

    try {

        Connection conn = Koneksi.getConnection();

        String sql = "SELECT * FROM ruangan";

        ResultSet rs =
            conn.createStatement().executeQuery(sql);

        while (rs.next()) {

            jComboBoxRuangan.addItem(
                rs.getInt("id_ruangan") + " - " +
                rs.getString("nama_ruangan")
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage());

    }
}

private void loadHari() {

    jComboBoxHari.removeAllItems();

    jComboBoxHari.addItem("Senin");
    jComboBoxHari.addItem("Selasa");
    jComboBoxHari.addItem("Rabu");
    jComboBoxHari.addItem("Kamis");
    jComboBoxHari.addItem("Jumat");
    jComboBoxHari.addItem("Sabtu");
}

private void loadJam() {

    jComboBoxJam.removeAllItems();

    jComboBoxJam.addItem("08.00");
    jComboBoxJam.addItem("10.00");
    jComboBoxJam.addItem("13.00");
    jComboBoxJam.addItem("15.00");
    jComboBoxJam.addItem("18.00");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJadwal = new javax.swing.JLabel();
        txtPengajar = new javax.swing.JLabel();
        txtSiswa = new javax.swing.JLabel();
        txtHari = new javax.swing.JLabel();
        txtJam = new javax.swing.JLabel();
        jComboBoxPengajar = new javax.swing.JComboBox<>();
        jComboBoxSiswa = new javax.swing.JComboBox<>();
        jComboBoxHari = new javax.swing.JComboBox<>();
        jComboBoxJam = new javax.swing.JComboBox<>();
        tmbKembali = new javax.swing.JButton();
        tmbSimpan = new javax.swing.JButton();
        txtRuangan = new javax.swing.JLabel();
        jComboBoxRuangan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJadwal.setText("FORM JADWAL");

        txtPengajar.setText("PENGAJAR");

        txtSiswa.setText("SISWA");

        txtHari.setText("HARI");

        txtJam.setText("JAM");

        jComboBoxPengajar.setBackground(new java.awt.Color(255, 102, 153));

        jComboBoxSiswa.setBackground(new java.awt.Color(255, 153, 204));

        jComboBoxHari.setBackground(new java.awt.Color(255, 102, 153));

        jComboBoxJam.setBackground(new java.awt.Color(255, 153, 204));

        tmbKembali.setBackground(new java.awt.Color(204, 255, 204));
        tmbKembali.setText("KEMBALI");
        tmbKembali.addActionListener(this::tmbKembaliActionPerformed);

        tmbSimpan.setBackground(new java.awt.Color(204, 255, 204));
        tmbSimpan.setText("SIMPAN");
        tmbSimpan.addActionListener(this::tmbSimpanActionPerformed);

        txtRuangan.setText("RUANGAN");

        jComboBoxRuangan.setBackground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtJadwal)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPengajar)
                            .addComponent(txtSiswa)
                            .addComponent(txtHari)
                            .addComponent(txtJam)
                            .addComponent(txtRuangan))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxHari, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxJam, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tmbSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tmbKembali)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtJadwal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPengajar)
                    .addComponent(jComboBoxPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSiswa)
                    .addComponent(jComboBoxSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbSimpan)
                    .addComponent(tmbKembali))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbSimpanActionPerformed
         try {

        Connection conn = Koneksi.getConnection();

        int id_pengajar =
            Integer.parseInt(
                jComboBoxPengajar
                .getSelectedItem()
                .toString()
                .split(" - ")[0]
            );

        int id_siswa =
            Integer.parseInt(
                jComboBoxSiswa
                .getSelectedItem()
                .toString()
                .split(" - ")[0]
            );

        int id_ruangan =
            Integer.parseInt(
                jComboBoxRuangan
                .getSelectedItem()
                .toString()
                .split(" - ")[0]
            );

        String hari =
            jComboBoxHari.getSelectedItem().toString();

        String jam =
            jComboBoxJam.getSelectedItem().toString();

        // MODE EDIT
        if (isEdit) {

            String sql =
                "UPDATE jadwal SET hari=?, jam=?, id_pengajar=?, id_ruangan=?, id_siswa=? " +
                "WHERE id_jadwal=?";

            PreparedStatement pst =
                conn.prepareStatement(sql);

            pst.setString(1, hari);
            pst.setString(2, jam);
            pst.setInt(3, id_pengajar);
            pst.setInt(4, id_ruangan);
            pst.setInt(5, id_siswa);
            pst.setInt(6, idJadwal);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "Data jadwal berhasil diupdate!");

        }

        // MODE TAMBAH
        else {

            String sql =
                "INSERT INTO jadwal(hari, jam, id_pengajar, id_ruangan, id_siswa) " +
                "VALUES (?, ?, ?, ?, ?)";

            PreparedStatement pst =
                conn.prepareStatement(sql);

            pst.setString(1, hari);
            pst.setString(2, jam);
            pst.setInt(3, id_pengajar);
            pst.setInt(4, id_ruangan);
            pst.setInt(5, id_siswa);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "Data jadwal berhasil disimpan!");
        }

        new datajadwal(email).setVisible(true);

        this.dispose();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage());

    }
    }//GEN-LAST:event_tmbSimpanActionPerformed

    private void tmbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbKembaliActionPerformed
          try {

        new datajadwal(email).setVisible(true);

        this.dispose();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage());

    }
    }//GEN-LAST:event_tmbKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> 
    new formjadwal("admin@gmail.com").setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxHari;
    private javax.swing.JComboBox<String> jComboBoxJam;
    private javax.swing.JComboBox<String> jComboBoxPengajar;
    private javax.swing.JComboBox<String> jComboBoxRuangan;
    private javax.swing.JComboBox<String> jComboBoxSiswa;
    private javax.swing.JButton tmbKembali;
    private javax.swing.JButton tmbSimpan;
    private javax.swing.JLabel txtHari;
    private javax.swing.JLabel txtJadwal;
    private javax.swing.JLabel txtJam;
    private javax.swing.JLabel txtPengajar;
    private javax.swing.JLabel txtRuangan;
    private javax.swing.JLabel txtSiswa;
    // End of variables declaration//GEN-END:variables
}
