package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

public class formruangan extends javax.swing.JFrame {
    private int idRuangan = 0;
    private boolean isEdit = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formruangan.class.getName());

    /**
     * Creates new form formruangan
     */
    public formruangan() {
        initComponents();
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    // Ambil panel utama
    javax.swing.JPanel panel = (javax.swing.JPanel) getContentPane();

    // Custom JLabel biar gambar auto resize
    javax.swing.JLabel background = new javax.swing.JLabel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
                getClass().getResource("/gambar/bg.png")
            );

            java.awt.Image img = icon.getImage();

            // Scale gambar sesuai ukuran window
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    };

    background.setLayout(new java.awt.GridBagLayout());

    setContentPane(background);

    panel.setOpaque(false);

    background.add(panel, new java.awt.GridBagConstraints());
    
        
        loadCombo();
    }
    
    public formruangan(int id, String nama, String kapasitas) {
    initComponents();
    loadCombo();

    this.idRuangan = id;
    this.isEdit = true;

    jComboBoxNamaRuangan.setSelectedItem(nama);
    jComboBoxKapasitas.setSelectedItem(kapasitas);

    tmbSimpan.setText("Update");
}
    
    private void loadCombo() {
    // nama ruangan
    jComboBoxNamaRuangan.addItem("Ruang A");
    jComboBoxNamaRuangan.addItem("Ruang B");
    jComboBoxNamaRuangan.addItem("Ruang C");

    // kapasitas
    jComboBoxKapasitas.addItem("10");
    jComboBoxKapasitas.addItem("12");
    jComboBoxKapasitas.addItem("15");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRuangan = new javax.swing.JLabel();
        txtNamaRuangan = new javax.swing.JLabel();
        jComboBoxNamaRuangan = new javax.swing.JComboBox<>();
        txtKapasitas = new javax.swing.JLabel();
        jComboBoxKapasitas = new javax.swing.JComboBox<>();
        tmbBatal = new javax.swing.JButton();
        tmbSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRuangan.setText("FORM RUANGAN");

        txtNamaRuangan.setText("NAMA RUANGAN");

        jComboBoxNamaRuangan.setBackground(new java.awt.Color(255, 102, 153));

        txtKapasitas.setText("KAPASITAS");

        jComboBoxKapasitas.setBackground(new java.awt.Color(255, 153, 204));

        tmbBatal.setBackground(new java.awt.Color(204, 255, 204));
        tmbBatal.setText("BATAL");
        tmbBatal.addActionListener(this::tmbBatalActionPerformed);

        tmbSimpan.setBackground(new java.awt.Color(204, 255, 204));
        tmbSimpan.setText("SIMPAN");
        tmbSimpan.addActionListener(this::tmbSimpanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tmbSimpan)
                        .addGap(29, 29, 29)
                        .addComponent(tmbBatal)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaRuangan)
                            .addComponent(txtKapasitas))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxNamaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRuangan)
                            .addComponent(jComboBoxKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtRuangan)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNamaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaRuangan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKapasitas))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbBatal)
                    .addComponent(tmbSimpan))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbSimpanActionPerformed
       try {
        Connection conn = Koneksi.getConnection();

        String nama = jComboBoxNamaRuangan.getSelectedItem().toString();
        int kapasitas = Integer.parseInt(jComboBoxKapasitas.getSelectedItem().toString());

        if (isEdit) {
            String sql = "UPDATE ruangan SET nama_ruangan=?, kapasitas=? WHERE id_ruangan=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, nama);
            pst.setInt(2, kapasitas);
            pst.setInt(3, idRuangan);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");

        } else {
            String sql = "INSERT INTO ruangan (nama_ruangan, kapasitas) VALUES (?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, nama);
            pst.setInt(2, kapasitas);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        }

        new dataruangan().setVisible(true);
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_tmbSimpanActionPerformed

    private void tmbBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbBatalActionPerformed
         new dataruangan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmbBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formruangan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxKapasitas;
    private javax.swing.JComboBox<String> jComboBoxNamaRuangan;
    private javax.swing.JButton tmbBatal;
    private javax.swing.JButton tmbSimpan;
    private javax.swing.JLabel txtKapasitas;
    private javax.swing.JLabel txtNamaRuangan;
    private javax.swing.JLabel txtRuangan;
    // End of variables declaration//GEN-END:variables
}
